# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.IntegerField()),
                ('login', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('gravatar_id', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('html_url', models.TextField(blank=True, null=True)),
                ('followers_url', models.TextField(blank=True, null=True)),
                ('following_url', models.TextField(blank=True, null=True)),
                ('gists_url', models.TextField(blank=True, null=True)),
                ('starred_url', models.TextField(blank=True, null=True)),
                ('subscriptions_url', models.TextField(blank=True, null=True)),
                ('organizations_url', models.TextField(blank=True, null=True)),
                ('repos_url', models.TextField(blank=True, null=True)),
                ('events_url', models.TextField(blank=True, null=True)),
                ('received_events_url', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('site_admin', models.BooleanField(default=False)),
                ('score', models.FloatField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'github_user',
            },
        ),
    ]
