# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubuser',
            name='api_call_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
